version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "chore(deps)"
    ignore:
      - dependency-name: "next"
        versions: [">14.2.30"]
    groups:
      nextjs-and-react:
        patterns:
          - "react"
          - "react-dom"
