/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { INonprofitDonation } from "./INonprofitDonation";
export type { ReentrantTreasury } from "./ReentrantTreasury";
