/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ReentrantTreasuryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOwnership"
      | "attackEnabled"
      | "attackWithdrawAll"
      | "reentryAttempts"
      | "reentryFailures"
      | "setAttackEnabled"
      | "target"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "attackEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "attackWithdrawAll",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reentryAttempts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reentryFailures",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAttackEnabled",
    values: [boolean]
  ): string;
  encodeFunctionData(functionFragment: "target", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "attackEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "attackWithdrawAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reentryAttempts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reentryFailures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAttackEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "target", data: BytesLike): Result;
}

export interface ReentrantTreasury extends BaseContract {
  connect(runner?: ContractRunner | null): ReentrantTreasury;
  waitForDeployment(): Promise<this>;

  interface: ReentrantTreasuryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  attackEnabled: TypedContractMethod<[], [boolean], "view">;

  attackWithdrawAll: TypedContractMethod<[], [void], "nonpayable">;

  reentryAttempts: TypedContractMethod<[], [bigint], "view">;

  reentryFailures: TypedContractMethod<[], [bigint], "view">;

  setAttackEnabled: TypedContractMethod<
    [enabled: boolean],
    [void],
    "nonpayable"
  >;

  target: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "attackEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "attackWithdrawAll"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reentryAttempts"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reentryFailures"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setAttackEnabled"
  ): TypedContractMethod<[enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "target"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
