/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  INonprofitDonation,
  INonprofitDonationInterface,
} from "../../../../contracts/test/ReentrantTreasury.sol/INonprofitDonation";

const _abi = [
  {
    inputs: [],
    name: "acceptOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawAll",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class INonprofitDonation__factory {
  static readonly abi = _abi;
  static createInterface(): INonprofitDonationInterface {
    return new Interface(_abi) as INonprofitDonationInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): INonprofitDonation {
    return new Contract(address, _abi, runner) as unknown as INonprofitDonation;
  }
}
